# Generated by Django 4.2.10 on 2025-12-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicte_admin', '0002_auto_20241118_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspector',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
